import type { ScanResult } from './types.js'
import { aggregateEdges, topLevelIds } from './graph.js'

export function toJson(result: ScanResult): string {
  return JSON.stringify(result, null, 2)
}

export function toMarkdown(result: ScanResult): string {
  const {
    repository,
    summary,
    health,
    stats,
    languages,
    frameworks,
    entryPoints,
    nodes,
    edges,
    warnings,
    dependencies,
  } = result
  const top = nodes.filter((n) => !n.parent)
  const byId = new Map(nodes.map((n) => [n.id, n]))
  const name = (id: string) => byId.get(id)?.name ?? id
  const moduleEdges = aggregateEdges(nodes, edges, topLevelIds(nodes))
  const lines: string[] = []
  const p = (s = '') => lines.push(s)

  p(`# ${repository.fullName} — architecture report`)
  p()
  p(
    `_Generated by RepoScope on ${new Date(repository.scannedAt).toLocaleString()}${repository.url ? ` from ${repository.url}` : ''}._`,
  )
  p()
  p(`**${summary.headline}**`)
  p()
  p(summary.description)
  p()
  p('## Overview')
  p()
  p('| Metric | Value |')
  p('| --- | --- |')
  p(`| Estimated health | ${health.score}/100 (${health.label}) |`)
  p(`| Files | ${stats.files} |`)
  p(`| Lines of code | ${stats.lines} |`)
  p(`| Modules | ${stats.modules} |`)
  p(`| Connections | ${stats.connections} |`)
  p(`| Warnings | ${stats.warnings} |`)
  p(
    `| Languages | ${languages.map((l) => `${l.name} (${Math.round(l.share * 100)}%)`).join(', ') || '—'} |`,
  )
  p(`| Frameworks | ${frameworks.join(', ') || '—'} |`)
  p(`| Entry points | ${entryPoints.map((e) => `\`${e}\``).join(', ') || '—'} |`)
  p()
  p('## Architecture')
  p()
  p(summary.architecture)
  p()
  p('### Components')
  p()
  p('| Component | Type | Path | Files | Depends on | Used by |')
  p('| --- | --- | --- | --- | --- | --- |')
  for (const n of [...top].sort((a, b) => b.importance - a.importance)) {
    p(
      `| ${n.name} | ${n.type} | \`${n.path}\` | ${n.meta?.files ?? ''} | ${n.dependencies.map(name).join(', ')} | ${n.dependents.map(name).join(', ')} |`,
    )
  }
  p()
  p('### Connections')
  p()
  p('```mermaid')
  p('graph LR')
  const mid = (id: string) => id.replace(/[^a-zA-Z0-9]/g, '_')
  for (const n of top) p(`  ${mid(n.id)}["${n.name.replace(/"/g, "'")}"]`)
  for (const e of moduleEdges) p(`  ${mid(e.source)} -->|${e.type}| ${mid(e.target)}`)
  p('```')
  p()
  const apiNodes = top.filter((n) => n.meta?.routes?.length)
  if (apiNodes.length) {
    p('### API routes')
    p()
    for (const n of apiNodes) {
      p(`**${n.name}** (\`${n.path}\`)`)
      p()
      for (const r of n.meta!.routes!) p(`- \`${r}\``)
      p()
    }
  }
  p('## Estimated health score')
  p()
  p(
    `**${health.score}/100 — ${health.label}.** This is a heuristic estimate, not a measured quality metric.`,
  )
  p()
  p('| Signal | Δ | Note |')
  p('| --- | --- | --- |')
  for (const b of health.breakdown) p(`| ${b.signal} | ${b.delta} | ${b.note} |`)
  p()
  const review = result.review
  if (review && review.suggestions.length) {
    p('## Code review')
    p()
    p(
      `${review.suggestions.length} findings from ${review.rulesRun} rules across ${review.filesInspected} source files. These are static heuristics with evidence attached — check each against the cited line before acting.`,
    )
    p()
    const order = ['critical', 'high', 'medium', 'low'] as const
    for (const severity of order) {
      const group = review.suggestions.filter((s) => s.severity === severity)
      if (!group.length) continue
      p(`### ${severity[0].toUpperCase()}${severity.slice(1)} (${group.length})`)
      p()
      for (const s of group) {
        p(`#### ${s.title}`)
        p()
        p(
          `\`${s.rule}\` · ${s.category} · ${s.effort}${s.confidence !== 'certain' ? ` · ${s.confidence}` : ''}`,
        )
        p()
        p(s.detail)
        p()
        p(`**What to do:** ${s.fix}`)
        p()
        if (s.evidence.length) {
          for (const e of s.evidence) {
            p(
              `- \`${e.path}${e.line ? ':' + e.line : ''}\`${e.excerpt ? ` — \`${e.excerpt.replace(/`/g, "'")}\`` : ''}`,
            )
          }
          if (s.occurrences && s.occurrences > s.evidence.length)
            p(`- …and ${s.occurrences - s.evidence.length} more`)
          p()
        }
      }
    }
  } else if (review) {
    p('## Code review')
    p()
    p(`No findings. ${review.rulesRun} rules ran across ${review.filesInspected} source files.`)
    p()
  }

  p('## Key findings')
  p()
  for (const f of summary.keyFindings) p(`- **${f.title}** (${f.kind}) — ${f.detail}`)
  p()
  p('## Warnings')
  p()
  if (!warnings.length) p('No warnings.')
  for (const w of warnings)
    p(`- **[${w.severity}] ${w.title}** — ${w.detail}${w.path ? ` (\`${w.path}\`)` : ''}`)
  p()
  p('## Recommended next actions')
  p()
  summary.nextActions.forEach((a, i) => p(`${i + 1}. ${a}`))
  p()
  const runtime = dependencies.filter((d) => !d.dev)
  if (runtime.length) {
    p('## Dependencies')
    p()
    p(
      `${runtime.length} runtime dependencies${dependencies.length - runtime.length ? `, ${dependencies.length - runtime.length} dev` : ''}.`,
    )
    p()
    p(runtime.map((d) => `\`${d.name}\`${d.used ? '' : ' (not imported)'}`).join(', '))
    p()
  }
  return lines.join('\n')
}
